name = "Create: Just for Fun"
author = "First-Non-Interesting-Username"
version = "2026.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37cf21b852ff37287853b6873060d34fe2a918e98040596e1f9cac072f647ea5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "saves/default/datapacks"
