name: Create github release
on:
  schedule:
    - cron: '45 17 * * 5'
  workflow_dispatch:
    inputs:
      tag_suffix:
        description: 'Optional suffix (e.g. -hotfix)'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Export to .mrpack
        uses: hudsonm62/packwiz-action@538bcd35d3a4810f35ef6f51b0b65be8191b28bf # v1
        with:
          args: modrinth export

      - name: Find exported .mrpack
        id: mrpack
        run: |
          FILE=$(find . -name "*.mrpack" | head -n 1)
          echo "path=$FILE" >> $GITHUB_OUTPUT

      - name: Get release name
        id: release_name
        run: echo "value=$(date +'%Y.%V')${{ github.event.inputs.tag_suffix }}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          tag_name: ${{ steps.release_name.outputs.value }}
          name: ${{ steps.release_name.outputs.value }}
          generate_release_notes: true
          files: ${{ steps.mrpack.outputs.path }}

      - name: Publish Modpack to Modrinth
        uses: cloudnode-pro/modrinth-publish@3870f66007063f03fb70118ca9eddbc09a4ba666 # v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 'Oz2C6Bff'
          version: ${{ steps.release_name.outputs.value }}
          files: ${{ steps.mrpack.outputs.path }}
          changelog: ${{ steps.create_release.outputs.body }}
          channel: 'release'
          loaders: 'neoforge'
          game-versions: |
            1.21.1